# Site settings
title: codexergosum
header-img: img/home-bg.png
email: gomezmontoya77@gmail.com
copyright_name: gomezmontoya
description: > # this means to ignore newlines until "baseurl:"
  A Humanities Professor Voyage into Coding  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gomezmontoya
learn_profile: gomezmontoya
email_username: gomezmontoya77@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
